### ISSUE TITLE
a05 APIs

### ISSUE THREAD

**Issue by mattsg6** [comp426-2022-spring/a05#1]
The assignment says - or I've at least interpreted it this way - that we need to change our existing APIs to use body instead of parameters. In the documentation, the APIs are written with the parameters still. Are we meant to keep the APIs with parameters and then create new APIs that accomplish the same task but using body instead? Or can we just change the APIs in the documentation? Just need some clarification.

**Comment by christineiym** [comment]
You probably have already figured it out, but given that the documentation for the API includes both endpoints using parameters (as you have noted) and endpoints doing the same things (but using the request body instead of parameters), it appears that we should add the modified endpoints without removing the other endpoints!

**Comment by mattsg6** [comment]
Yep! I made that assumption. Appreciate the response.
